/** @file sorter_options.h
 *  @brief The header file for the command line option parser
 *  generated by GNU Gengetopt version 2.22.4
 *  http://www.gnu.org/software/gengetopt.
 *  DO NOT modify this file, since it can be overwritten
 *  @author GNU Gengetopt by Lorenzo Bettini */

#ifndef SORTER_OPTIONS_H
#define SORTER_OPTIONS_H

/* If we use autoconf.  */
#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#include <stdio.h> /* for FILE */

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#ifndef CMDLINE_PARSER_PACKAGE
/** @brief the program name (used for printing errors) */
#define CMDLINE_PARSER_PACKAGE "Sorter"
#endif

#ifndef CMDLINE_PARSER_PACKAGE_NAME
/** @brief the complete program name (used for help and version) */
#define CMDLINE_PARSER_PACKAGE_NAME "Sorter"
#endif

#ifndef CMDLINE_PARSER_VERSION
/** @brief the program version */
#define CMDLINE_PARSER_VERSION "1.0"
#endif

enum enum_serial_algorithm { serial_algorithm_arg_bubble = 0 , serial_algorithm_arg_merge, serial_algorithm_arg_quick, serial_algorithm_arg_shell };

/** @brief Where the command line options are stored */
struct gengetopt_args_info
{
  const char *help_help; /**< @brief Print help and exit help description.  */
  const char *version_help; /**< @brief Print version and exit help description.  */
  char * input_arg;	/**< @brief Folder with the files to sort.  */
  char * input_orig;	/**< @brief Folder with the files to sort original value given at command line.  */
  const char *input_help; /**< @brief Folder with the files to sort help description.  */
  char * output_arg;	/**< @brief Folder to put the sorted files.  */
  char * output_orig;	/**< @brief Folder to put the sorted files original value given at command line.  */
  const char *output_help; /**< @brief Folder to put the sorted files help description.  */
  enum enum_serial_algorithm *serial_algorithm_arg;	/**< @brief Algorithms to use in the sort process.  */
  char ** serial_algorithm_orig;	/**< @brief Algorithms to use in the sort process original value given at command line.  */
  unsigned int serial_algorithm_min; /**< @brief Algorithms to use in the sort process's minimum occurreces */
  unsigned int serial_algorithm_max; /**< @brief Algorithms to use in the sort process's maximum occurreces */
  const char *serial_algorithm_help; /**< @brief Algorithms to use in the sort process help description.  */
  char * log_arg;	/**< @brief Filename to log the messages.  */
  char * log_orig;	/**< @brief Filename to log the messages original value given at command line.  */
  const char *log_help; /**< @brief Filename to log the messages help description.  */
  int daemon_flag;	/**< @brief Use program as a daemon (default=off).  */
  const char *daemon_help; /**< @brief Use program as a daemon help description.  */
  char * time_server_addr_arg;	/**< @brief IP address of the UDP time server.  */
  char * time_server_addr_orig;	/**< @brief IP address of the UDP time server original value given at command line.  */
  const char *time_server_addr_help; /**< @brief IP address of the UDP time server help description.  */
  int time_server_port_arg;	/**< @brief The port of the UDP time server.  */
  char * time_server_port_orig;	/**< @brief The port of the UDP time server original value given at command line.  */
  const char *time_server_port_help; /**< @brief The port of the UDP time server help description.  */
  char * stats_server_arg;	/**< @brief IP address of the UDP server to publish the results.  */
  char * stats_server_orig;	/**< @brief IP address of the UDP server to publish the results original value given at command line.  */
  const char *stats_server_help; /**< @brief IP address of the UDP server to publish the results help description.  */
  int stats_port_arg;	/**< @brief The port of the UDP server to publish the results.  */
  char * stats_port_orig;	/**< @brief The port of the UDP server to publish the results original value given at command line.  */
  const char *stats_port_help; /**< @brief The port of the UDP server to publish the results help description.  */
  
  unsigned int help_given ;	/**< @brief Whether help was given.  */
  unsigned int version_given ;	/**< @brief Whether version was given.  */
  unsigned int input_given ;	/**< @brief Whether input was given.  */
  unsigned int output_given ;	/**< @brief Whether output was given.  */
  unsigned int serial_algorithm_given ;	/**< @brief Whether serial-algorithm was given.  */
  unsigned int log_given ;	/**< @brief Whether log was given.  */
  unsigned int daemon_given ;	/**< @brief Whether daemon was given.  */
  unsigned int time_server_addr_given ;	/**< @brief Whether time-server-addr was given.  */
  unsigned int time_server_port_given ;	/**< @brief Whether time-server-port was given.  */
  unsigned int stats_server_given ;	/**< @brief Whether stats-server was given.  */
  unsigned int stats_port_given ;	/**< @brief Whether stats-port was given.  */

  int Daemon_mode_counter; /**< @brief Counter for mode Daemon */
  int UDP_report_mode_counter; /**< @brief Counter for mode UDP_report */
  int UDP_time_mode_counter; /**< @brief Counter for mode UDP_time */
} ;

/** @brief The additional parameters to pass to parser functions */
struct cmdline_parser_params
{
  int override; /**< @brief whether to override possibly already present options (default 0) */
  int initialize; /**< @brief whether to initialize the option structure gengetopt_args_info (default 1) */
  int check_required; /**< @brief whether to check that all required options were provided (default 1) */
  int check_ambiguity; /**< @brief whether to check for options already specified in the option structure gengetopt_args_info (default 0) */
  int print_errors; /**< @brief whether getopt_long should print an error message for a bad option (default 1) */
} ;

/** @brief the purpose string of the program */
extern const char *gengetopt_args_info_purpose;
/** @brief the usage string of the program */
extern const char *gengetopt_args_info_usage;
/** @brief all the lines making the help output */
extern const char *gengetopt_args_info_help[];

/**
 * The command line parser
 * @param argc the number of command line options
 * @param argv the command line options
 * @param args_info the structure where option information will be stored
 * @return 0 if everything went fine, NON 0 if an error took place
 */
int cmdline_parser (int argc, char **argv,
  struct gengetopt_args_info *args_info);

/**
 * The command line parser (version with additional parameters - deprecated)
 * @param argc the number of command line options
 * @param argv the command line options
 * @param args_info the structure where option information will be stored
 * @param override whether to override possibly already present options
 * @param initialize whether to initialize the option structure my_args_info
 * @param check_required whether to check that all required options were provided
 * @return 0 if everything went fine, NON 0 if an error took place
 * @deprecated use cmdline_parser_ext() instead
 */
int cmdline_parser2 (int argc, char **argv,
  struct gengetopt_args_info *args_info,
  int override, int initialize, int check_required);

/**
 * The command line parser (version with additional parameters)
 * @param argc the number of command line options
 * @param argv the command line options
 * @param args_info the structure where option information will be stored
 * @param params additional parameters for the parser
 * @return 0 if everything went fine, NON 0 if an error took place
 */
int cmdline_parser_ext (int argc, char **argv,
  struct gengetopt_args_info *args_info,
  struct cmdline_parser_params *params);

/**
 * Save the contents of the option struct into an already open FILE stream.
 * @param outfile the stream where to dump options
 * @param args_info the option struct to dump
 * @return 0 if everything went fine, NON 0 if an error took place
 */
int cmdline_parser_dump(FILE *outfile,
  struct gengetopt_args_info *args_info);

/**
 * Save the contents of the option struct into a (text) file.
 * This file can be read by the config file parser (if generated by gengetopt)
 * @param filename the file where to save
 * @param args_info the option struct to save
 * @return 0 if everything went fine, NON 0 if an error took place
 */
int cmdline_parser_file_save(const char *filename,
  struct gengetopt_args_info *args_info);

/**
 * Print the help
 */
void cmdline_parser_print_help(void);
/**
 * Print the version
 */
void cmdline_parser_print_version(void);

/**
 * Initializes all the fields a cmdline_parser_params structure 
 * to their default values
 * @param params the structure to initialize
 */
void cmdline_parser_params_init(struct cmdline_parser_params *params);

/**
 * Allocates dynamically a cmdline_parser_params structure and initializes
 * all its fields to their default values
 * @return the created and initialized cmdline_parser_params structure
 */
struct cmdline_parser_params *cmdline_parser_params_create(void);

/**
 * Initializes the passed gengetopt_args_info structure's fields
 * (also set default values for options that have a default)
 * @param args_info the structure to initialize
 */
void cmdline_parser_init (struct gengetopt_args_info *args_info);
/**
 * Deallocates the string fields of the gengetopt_args_info structure
 * (but does not deallocate the structure itself)
 * @param args_info the structure to deallocate
 */
void cmdline_parser_free (struct gengetopt_args_info *args_info);

/**
 * Checks that all the required options were specified
 * @param args_info the structure to check
 * @param prog_name the name of the program that will be used to print
 *   possible errors
 * @return
 */
int cmdline_parser_required (struct gengetopt_args_info *args_info,
  const char *prog_name);

extern const char *cmdline_parser_serial_algorithm_values[];  /**< @brief Possible values for serial-algorithm. */


#ifdef __cplusplus
}
#endif /* __cplusplus */
#endif /* SORTER_OPTIONS_H */
